# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design CNT__parameterized3 has unconnected port RES}}  -suppress 
set_msg_config  -id {Synth 8-3331}  -string {{WARNING: [Synth 8-3331] design SIPO__parameterized1 has unconnected port RES}}  -suppress 
set_msg_config  -id {Synth 8-3331}  -suppress 
create_project -in_memory -part xc7a15tfgg484-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/vhdl/pjrs/pjr1/project_8/project_8.cache/wt [current_project]
set_property parent.project_path F:/vhdl/pjrs/pjr1/project_8/project_8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo f:/vhdl/pjrs/pjr1/project_8/project_8.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  F:/vhdl/pjrs/pjr1/project_8/project_8.srcs/sources_1/new/COMP_EQ.vhd
  F:/vhdl/pjrs/pjr1/project_8/project_8.srcs/sources_1/new/D_FLIPFLOP.vhd
  F:/vhdl/pjrs/pjr1/project_8/project_8.srcs/sources_1/new/SIPO.vhd
  F:/vhdl/pjrs/pjr1/project_8/project_8.srcs/sources_1/new/vhdl.vhd
  F:/vhdl/pjrs/pjr1/project_8/project_8.srcs/sources_1/new/Debouncer.vhd
  F:/vhdl/pjrs/pjr1/project_8/project_8.srcs/sources_1/new/MUX4_1.vhd
  F:/vhdl/pjrs/pjr1/project_8/project_8.srcs/sources_1/new/MUX2_1.vhd
  F:/vhdl/pjrs/pjr1/project_8/project_8.srcs/sources_1/new/T_FLIPFLOP.vhd
  F:/vhdl/pjrs/pjr1/project_8/project_8.srcs/sources_1/new/MAIN.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MAIN -part xc7a15tfgg484-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MAIN.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MAIN_utilization_synth.rpt -pb MAIN_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
